GET http://localhost:4004/odata/v4/employee/employee HTTP/1.1

### 

POST http://localhost:4004/odata/v4/employee/employee HTTP/1.1
Content-Type: application/json

{
"employeeID" : "1001",
    "name" : "Vishal",
    "dob" : "18/10/1997",
    "mobno" : "123456789",
    "experience" : 4.2
}


###

DELETE http://localhost:4004/odata/v4/employee/employee(employeeID='1001') HTTP/1.1